concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  could-deployment-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache-dependency-path: '**/pom.xml'
        check-latest: true
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          ~/.m2/wrapper/

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: build docker image
      run: .ci/infrastructure-docker-build.sh docker ${{ matrix.jdk_base_image }}
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        repository: CorfuDB/corfudb-cloud
    - continue-on-error: true
      name: install helm package manager
      run: 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

        chmod 700 get_helm.sh

        ./get_helm.sh


        helm repo add jetstack https://charts.jetstack.io

        helm repo update

        '
      working-directory: ./cloud/corfu
    - continue-on-error: true
      name: Create k3d Cluster
      uses: AbsaOSS/k3d-action@v2
      with:
        args: --volume /tmp/k3dvol:/tmp/k3dvol --agents 2 --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
        cluster-name: corfu
    - continue-on-error: true
      name: install corfu package
      run: 'helm install cert-manager jetstack/cert-manager --namespace cert-manager
        --create-namespace --version v1.8.0 --set installCRDs=true


        helm install corfu corfu --set persistence.enabled=true --set global.replicas=3
        --set image.pullPolicy=IfNotPresent --set image.registry=""


        sleep 120

        '
      working-directory: ./cloud/corfu
    - continue-on-error: true
      name: check deployment status
      run: "echo check deployment status:\nif kubectl get pods | grep \"corfu-0\"\
        ; then\n  echo \"Successful deployment!\"\n  exit 0\nelse\n  echo \"Failed\
        \ deployment!\"\n\n  echo pods:\n  kubectl get pods\n\n  echo corfu pod:\n\
        \  kubectl describe pod corfu-0\n\n  exit 1\nfi\n"
      working-directory: ./cloud/corfu
    strategy:
      matrix:
        jdk_base_image_version:
        - openjdk:11-jdk-bullseye
        - openjdk:17-jdk-bullseye
name: Cloud Deployment Test
on:
  repository_dispatch:
    types: trigger-ga___cloud-deployment-test.yml
