concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  integration_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          ~/.m2/wrapper/

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: build corfu
      run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -T 1C -q
    - continue-on-error: true
      name: run integration tests
      run: ./mvnw -pl :test clean verify -Pit -DskipTests
name: Integration Test
on:
  repository_dispatch:
    types: trigger-ga___integration-test.yml
