concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish_corfu_db_artifacts:
    env:
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache-dependency-path: '**/pom.xml'
        check-latest: true
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          ~/.m2/wrapper/

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Prepare Corfu
      run: '.ci/infrastructure-docker-build.sh docker

        .ci/generator-docker-build.sh

        '
      shell: bash
    - continue-on-error: true
      name: Publish corfu artifacts
      run: ./mvnw clean deploy -s ./.mvn/settings.xml -DskipTests -Dmaven.javadoc.skip=true
        -Dcheckstyle.skip -T 1C
      working-directory: ./
name: CorfuDB Artifacts
on:
  repository_dispatch:
    types: trigger-ga___publish-corfu.yml
