concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  universe_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache-dependency-path: '**/pom.xml'
        check-latest: true
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          ~/.m2/wrapper/

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Prepare Corfu
      run: .ci/infrastructure-docker-build.sh docker
      shell: bash
    - continue-on-error: true
      name: Run universe tests
      run: './mvnw -Dmaven.javadoc.skip=true -DskipTests -T 1C clean install

        ./mvnw -pl :universe -Puniverse -Dmaven.javadoc.skip=true verify

        '
name: Universe Test
on:
  repository_dispatch:
    types: trigger-ga___universe-test.yml
